// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajqoymqeguaavkujpdom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcW95bXFlZ3VhYXZrdWpwZG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDYwNDEsImV4cCI6MjA2MjIyMjA0MX0.q-81PTe_r25K7tcs8gWq2a7nE2e4HZCUY5qrKKCIvfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);